### ISSUE TITLE
EquinoxLaunchConfiguration (RAP launcher) always fails with "The org.eclipse.osgi plug-in is missing from this configuration." 

### ISSUE THREAD

**Issue by wimjongman** [eclipse-pde/eclipse.pde.ui#30]
From: [Bugzilla 579708](https://bugs.eclipse.org/bugs/show_bug.cgi?id=579708) by @ifurnadjiev 

RAP launcher (based on org.eclipse.pde.launching.EquinoxLaunchConfiguration) is broken after the change https://git.eclipse.org/r/c/pde/eclipse.pde.ui/+/186860

Before the change in org.eclipse.pde.launching.EquinoxLaunchConfiguration.preLaunchCheck(ILaunchConfiguration, ILaunch, IProgressMonitor) the missing OSGi bundle has been added to fModels and fAllBundles automatically. After the change the code:
    if (!RequirementHelper.addApplicationLaunchRequirements(fModels, configuration)) {
			throw new CoreException(Status.error(PDEMessages.EquinoxLaunchConfiguration_oldTarget));
		}
always throws. For normal operation RequirementHelper.addApplicationLaunchRequirements returns false (as the missingRequirements there is false ).

For RAP launcher (RAP Tools) this issue is a blocker!

**Comment by wimjongman** [comment]
@ifurnadjiev can you provide a PR for this?

**Comment by ifurnadjiev** [comment]
Unfortunately, I don't have an idea how to fix it.

**Comment by ifurnadjiev** [comment]
You can easily reproduce it by creating a new plugin project from "New Project Wizard" based on "View contribution using 3.x API" and run it as "OSGi Framework".

**Comment by ifurnadjiev** [comment]
Probably the author of the change (Hannes Wellmann) can review the code once again and provide a fix.

**Comment by wimjongman** [comment]
@HannesWell can you take a look?

**Comment by vik-chand** [comment]
I was assigning to myself by mistake. Now assigned to @HannesWell

**Comment by HannesWell** [comment]
Thanks for the report. This was indeed a silly bug. The boolean condition in the `preLaunchCheck()` method was just wrong.
I have created PR #31 to fix this.Please feel free to test the PR.

**Comment by wimjongman** [comment]
@ifurnadjiev is this issue fixed?

**Comment by ifurnadjiev** [comment]
I didn't test it yet. Will let you know if the problem (or other) persists.
